[tool.poetry]
name = "temporal-starter"
version = "0.1.0"
description = ""
authors = ["Arnaud Camuset <arnaud.camuset@free.fr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
httpx="0.28.1"
temporalio="1.21.1"
pydantic="2.12.5"
pydantic_settings="2.12.0"
ulid="1.1"
loguru="0.7.3"

[tool.poetry.group.dev.dependencies]
black = "^24.1.1"
flake8 = "^7.0.0"
isort = "^5.13.2"
mypy = "^1.8.0"
pylint = "^3.0.3"



[tool.poetry.group.test.dependencies]
pytest = "^9.0.0"
pytest-asyncio="1.3.0"
faker = "^22.6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
